# create_sqlite_db.py

# E. D'Souza
# Final part of the pipeline
# Takes the data generated by VEP from ClinVar and gnomAD
# Creates a sqlite3 database with the data

# from sqlalchemy import create_engine
# from sqlalchemy.schema import CreateTable

# sql_url = "sqlite:///:memory:"
# db_engine = create_engine(sql_url)
# table_sql = CreateTable(Foo.table).compile(db_engine)
