#!/bin/bash

# Runs VEP + UTR Annotator on all possible variants
# generated by generate_all_possible_variants.py

INPATH='../../data/pipeline/vep_data/input'
OUTPATH='../../data/pipeline/vep_data/output'
VEP_CACHE='/well/whiffin/shared/vep'
ASSEMBLY='GRCh38'
MANE_VERSION='0.93'

for i in {1..22} X Y
do
    echo "Running VEP with UTR annotator on chr ${i}"
    vep \
    --assembly GRCh38\
    --force_overwrite\
    --species homo_sapiens\
    --cache \
    --fasta ${VEP_CACHE}/Homo_sapiens.GRCh38.dna.primary_assembly.fa\
    --mane \
    --mane_select\
    --canonical\
    --offline\
    --tab \
    --dir_cache ${VEP_CACHE} \
    --plugin UTRannotator\
    -i ${INPATH}/UTR_variants_all_possible_${ASSEMBLY}_${MANE_VERSION}_chr${i}.txt\
    -o ${OUTPATH}/UTR_variants_vep_all_possible_${ASSEMBLY}_${MANE_VERSION}_chr${i}.txt
done