version: "3.7"
services:
  app:
    build: flask-app
    hostname: VuTR
    container_name: VuTR
    restart: unless-stopped  
    ports:
      - "5000:5000"
    volumes:
      - "../data/database/features.db:/db/features.db"
      - "../data/database/variant_store.db:/db/variant_store.db"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://vutr:5000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - PYTHONUNBUFFERED=1
